
#pragma once

//=== Macro cleanup =============================================================

#ifdef GINT_DETAIL_HEADER_PASS_ACTIVE

#    undef GINT_UNLIKELY
#    undef GINT_LIKELY
#    undef GINT_THROW
#    undef GINT_DETAIL_EXCEPTIONS_ENABLED
#    undef GINT_DETAIL_DIVZERO_CHECKS
#    undef GINT_ZERO_CHECK
#    undef GINT_DIVZERO_CHECK
#    undef GINT_MODZERO_CHECK
#    undef GINT_CONSTEXPR14
#    undef GINT_FORCE_INLINE
#    undef GINT_CLANG_NOINLINE
#    undef GINT_NOINLINE
#    undef GINT_COLD
#    undef GINT_HIDDEN_VISIBILITY
#    undef GINT_RESTRICT
#    undef GINT_DETAIL_HAS_BUILTIN
#    undef GINT_HAS_IS_CONSTANT_EVALUATED
#    undef GINT_ARCH_AARCH64
#    undef GINT_ARCH_X86_64
#    undef GINT_DETAIL_X86_64_GCC
#    undef GINT_DETAIL_X86_64_CLANG
#    undef GINT_DETAIL_X86_64_CARRY_INTRINSICS
#    undef GINT_DETAIL_AARCH64_GCC
#    undef GINT_DETAIL_AARCH64_CLANG
#    undef GINT_DETAIL_X86_64_CONSTEXPR_INTRINSICS_SAFE
#    undef GINT_AARCH64_INT128_NEGATIVE_ZERO_DIV_ATTR
#    undef GINT_WIDE_SHIFT_INLINE
#    undef GINT_WIDE_PARSE_INLINE
#    undef GINT_DETAIL_GCC_TUNED_POLICY
#    undef GINT_DETAIL_CLANG_TUNED_POLICY
#    undef GINT_DETAIL_AARCH64_ASM_POLICY
#    undef GINT_DETAIL_CONFIG_NAMESPACE_I
#    undef GINT_DETAIL_CONFIG_NAMESPACE_II
#    undef GINT_DETAIL_CONFIG_NAMESPACE
#    undef GINT_DETAIL_HEADER_PASS_ACTIVE
#endif
