name: CI

on:
  push:
    branches: ["**"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y cmake build-essential clang-format \
              libfmt-dev libgtest-dev libboost-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install cmake clang-format fmt googletest boost
          fi
      - name: Configure
        run: cmake -S . -B build -DGINT_BUILD_TESTS=ON -DGINT_BUILD_BENCHMARKS=OFF
      - name: Build
        run: cmake --build build --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
      - name: Check code format
        run: |
          FILES=$(git ls-files '*.cpp' '*.hpp' '*.h')
          if [ -n "$FILES" ]; then
            clang-format -i --style=file $FILES
            git diff --exit-code
          fi


  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-format \
            libfmt-dev libgtest-dev lcov libboost-dev
      - name: Configure
        run: cmake -S . -B build -DENABLE_COVERAGE=ON -DGINT_BUILD_TESTS=ON -DGINT_BUILD_BENCHMARKS=OFF
      - name: Build
        run: cmake --build build --config Debug
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure || true
      - name: Generate coverage
        run: |
          lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
          lcov --list coverage.info

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libfmt-dev libbenchmark-dev libboost-dev
      - name: Configure
        run: cmake -S . -B build -DGINT_BUILD_TESTS=OFF -DGINT_BUILD_BENCHMARKS=ON
      - name: Build
        run: cmake --build build --config Release
      - name: Run benchmarks
        run: |
          build/perf --benchmark_min_time=0.01s
          build/perf_compare_int256 --benchmark_min_time=0.01s

  build_centos83:
    name: Build (CentOS 8.3)
    runs-on: ubuntu-latest
    container:
      image: centos:8.3.2011
    steps:
      - uses: actions/checkout@v3

      - name: Prepare repos (EOL -> vault)
        run: |
          set -eux
          sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
          dnf -y clean all
          dnf -y makecache

      - name: Install toolchain & deps (no system cmake)
        run: |
          set -eux
          dnf -y install epel-release
          dnf -y install 'dnf-command(config-manager)' || dnf -y install dnf-plugins-core
          dnf config-manager --set-enabled powertools || dnf config-manager --set-enabled PowerTools
          dnf -y install gcc gcc-c++ make git wget curl tar \
                         clang clang-tools-extra \
                         fmt-devel boost-devel

      - name: Install CMake (Kitware prebuilt)
        run: |
          set -eux
          CMAKE_VER=3.27.9
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64)  PKG=linux-x86_64 ;;
            aarch64) PKG=linux-aarch64 ;;
            *) echo "Unsupported arch: $ARCH"; exit 1;;
          esac
          curl -L -o cmake.tgz https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}-${PKG}.tar.gz
          tar -xzf cmake.tgz
          CMAKE_BIN="$PWD/cmake-${CMAKE_VER}-${PKG}/bin"
          echo "$CMAKE_BIN" >> "$GITHUB_PATH"

      - name: Install GoogleTest (build from source)
        run: |
          set -eux
          GTEST_VER=1.12.0
          wget -qO gtest.tar.gz https://github.com/google/googletest/archive/refs/tags/v${GTEST_VER}.tar.gz
          tar -xzf gtest.tar.gz
          cmake -S googletest-${GTEST_VER} -B build-gtest -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
          cmake --build build-gtest --target install -j"$(nproc)"
          ldconfig

      - name: Configure
        run: cmake -S . -B build -DGINT_BUILD_TESTS=ON -DGINT_BUILD_BENCHMARKS=OFF

      - name: Build
        run: cmake --build build --config Debug -j"$(nproc)" --verbose

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Check code format
        run: |
          FILES=$(git ls-files '*.cpp' '*.hpp' '*.h') || true
          if [ -n "$FILES" ]; then
            clang-format -i --style=file $FILES
            git diff --exit-code
          fi

